apiVersion: v1
kind: BuildConfig
metadata:
  name: hello-rest-configmap-pipeline
  labels:
    name: hello-rest
spec:
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node ("maven") {                        
          stage ("Update configmap") {            
            sh "curl https://raw.githubusercontent.com/eljeko/spring-boot-binary-deploy-sample/master/pipelines/configuration/hello-rest.properties -o hello-rest.properties"              
            sh "oc create configmap hello-rest-config --from-file=hello-rest.properties --dry-run -o yaml|oc replace -n hello-rest -f -"
          }         
        }